packages:
  - .
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/client': true
  '@swc/core': true
  '@temporalio/core-bridge': true
  better-sqlite3: true
  esbuild: true
  nx: true
  protobufjs: true
